let
    Origine = Excel.Workbook(File.Contents("C:\Users\camil\Desktop\EPICODE\POWERBI\S9L2\M3S1E2.xlsx"), null, true),
    Ordini_Sheet = Origine{[Item="Ordini",Kind="Sheet"]}[Data],
    #"Intestazioni alzate di livello" = Table.PromoteHeaders(Ordini_Sheet, [PromoteAllScalars=true]),
    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"dqwdqw", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type text}, {"Column8", type text}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}}),
    #"Rimosse prime righe" = Table.Skip(#"Modificato tipo",2),
    #"Rimosse colonne" = Table.RemoveColumns(#"Rimosse prime righe",{"Column2", "Column3", "Column9"}),
    #"Intestazioni alzate di livello1" = Table.PromoteHeaders(#"Rimosse colonne", [PromoteAllScalars=true]),
    #"Modificato tipo1" = Table.TransformColumnTypes(#"Intestazioni alzate di livello1",{{"COD PROD", type text}, {"Collaboratore", type text}, {"Regione", type text}, {"Column4", type date}, {"Categoria", type text}, {"Prodotto", type text}, {"Prezzo unitario", type number}, {"Quantità", Int64.Type}}),
    #"Rinominate colonne" = Table.RenameColumns(#"Modificato tipo1",{{"Column4", "Data"}}),
    #"Modificato tipo2" = Table.TransformColumnTypes(#"Rinominate colonne",{{"Data", type date}}),
    #"Testo troncato" = Table.TransformColumns(#"Modificato tipo2",{{"Categoria", Text.Trim, type text}, {"Regione", Text.Trim, type text}, {"COD PROD", Text.Trim, type text}, {"Prodotto", Text.Trim, type text}}),
    #"Merge di colonne" = Table.CombineColumns(#"Testo troncato",{"Categoria", "Prodotto"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"CATPROD"),
    #"Rimossi errori" = Table.RemoveRowsWithErrors(#"Merge di colonne", {"Quantità"}),
    #"Sostituito valore" = Table.ReplaceValue(#"Rimossi errori",null,0,Replacer.ReplaceValue,{"Quantità"}),
    #"Colonna condizionale aggiunta" = Table.AddColumn(#"Sostituito valore", "Q>20", each if [Quantità] > 20 then "TROVATO" else "NON TROVATO"),
    #"Duplicata colonna" = Table.DuplicateColumn(#"Colonna condizionale aggiunta", "Quantità", "Quantità - Copia"),
    #"Rimosse colonne1" = Table.RemoveColumns(#"Duplicata colonna",{"Quantità - Copia"}),
    #"Aggiunta colonna personalizzata" = Table.AddColumn(#"Rimosse colonne1", "Totale", each [Prezzo unitario]*[Quantità]),
    #"Riordinate colonne" = Table.ReorderColumns(#"Aggiunta colonna personalizzata",{"COD PROD", "Collaboratore", "Regione", "Data", "CATPROD", "Prezzo unitario", "Quantità", "Totale", "Q>20"}),
    #"Rinominate colonne1" = Table.RenameColumns(#"Riordinate colonne",{{"Data", "Data ordine"}}),
    #"Riordinate colonne1" = Table.ReorderColumns(#"Rinominate colonne1",{"COD PROD", "Collaboratore", "Data ordine", "Regione", "CATPROD", "Prezzo unitario", "Quantità", "Totale", "Q>20"}),
    #"Ordinate righe" = Table.Sort(#"Riordinate colonne1",{{"Collaboratore", Order.Ascending}}),
    #"Testo troncato1" = Table.TransformColumns(#"Ordinate righe",{{"Collaboratore", Text.Trim, type text}}),
    #"Pulito testo" = Table.TransformColumns(#"Testo troncato1",{{"Collaboratore", Text.Clean, type text}}),
    #"Ordinate righe1" = Table.Sort(#"Pulito testo",{{"Collaboratore", Order.Ascending}}),
    #"Aggiunta colonna indice" = Table.AddIndexColumn(#"Ordinate righe1", "Indice", 0, 1, Int64.Type),
    #"Rimosse colonne2" = Table.RemoveColumns(#"Aggiunta colonna indice",{"Indice"}),
    #"Pulito testo1" = Table.TransformColumns(#"Rimosse colonne2",{{"Collaboratore", Text.Clean, type text}}),
    #"Filtrate righe" = Table.SelectRows(#"Pulito testo1", each ([Collaboratore] <> "Fove Anna")),
    #"Duplicata colonna1" = Table.DuplicateColumn(#"Filtrate righe", "COD PROD", "COD PROD - Copia"),
    #"Rinominate colonne2" = Table.RenameColumns(#"Duplicata colonna1",{{"COD PROD - Copia", "COD PROD - CIFRE"}}),
    #"Caratteri finali estratti" = Table.TransformColumns(#"Rinominate colonne2", {{"COD PROD - CIFRE", each Text.End(_, 4), type text}}),
    #"Aggiunta colonna personalizzata1" = Table.AddColumn(#"Caratteri finali estratti", "IVA", each [Prezzo unitario]*0.22),
    #"Rimosse colonne3" = Table.RemoveColumns(#"Aggiunta colonna personalizzata1",{"IVA"}),
    #"Aggiunta colonna personalizzata2" = Table.AddColumn(#"Rimosse colonne3", "IVA", each [Totale]*0.22),
    #"Rimosse colonne4" = Table.RemoveColumns(#"Aggiunta colonna personalizzata2",{"IVA"}),
    #"Aggiunta colonna personalizzata3" = Table.AddColumn(#"Rimosse colonne4", "IVA", each [Totale]*0.22),
    #"Inserito arrotondamento" = Table.AddColumn(#"Aggiunta colonna personalizzata3", "Arrotonda", each Number.Round([IVA], 2), type number),
    #"Rimosse colonne5" = Table.RemoveColumns(#"Inserito arrotondamento",{"IVA"}),
    #"Rinominate colonne3" = Table.RenameColumns(#"Rimosse colonne5",{{"Arrotonda", "IVA"}})
in
    #"Rinominate colonne3"